apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gcs-web-server.name" . }}
  labels:
    {{- include "gcs-web-server.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ include "serviceAccount.email" . | quote }}

