apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gcs-web-server.name" .}}
  annotations:
    networking.gke.io/managed-certificates: {{ include "gcs-web-server.name" . | quote }}
    kubernetes.io/ingress.global-static-ip-name: {{ include "IpAddress.name" . | quote}}
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: "redirect-https"
spec:
  defaultBackend:
    service:
      name: {{ include "gcs-web-server.name" .}}
      port:
        number: 80

---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: redirect-https
spec:
  redirectToHttps:
    enabled: true
