version: 3
tasks:
  default:
    silent: true
    desc: Lists all commands available
    cmds:
      - task --list-all
  terraform-validate:
    silent: true
    desc: Runs a terraform validate
    cmds:
      - terraform validate
  terraform-fmt:
    silent: true
    desc: Runs a terraform Format
    cmds:
      - terraform fmt
  vars:
    silent: true
    desc: Generates terraform.tfvars file
    cmds:
      - terraform-docs tfvars hcl . > terraform.tfvars