apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcs-website
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: gcs-website
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gcs-website
    spec:
      volumes:
        - name: gcs
          emptyDir: {}
      serviceAccountName: gcs-website
      containers:
        - name: gcs-website
          image: "userbradley/gcs-web-server"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - mountPath: /var/www/site
              name: gcs
          lifecycle:
            postStart:
              exec:
                command: [ "gcsfuse","--implicit-dirs", "-o", "allow_other", "gcs-website", "/var/www/site" ]
            preStop:
              exec:
                command: [ "fusermount", "-u", "/var/www/site/" ]